name: Relay e2e tests, health check
on:
  schedule:
    - cron: 0 9 * * *
jobs:
  relay_health: 
    uses: ./.github/workflows/playwright.yml
    with:
      environment: stage
      health_check: true
    secrets: inherit
    